"""add capture uniqueness constraints

Revision ID: 03b2175f033b
Revises: 004b83fcafcb
Create Date: 2026-10-01 12:42:48.406585

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03b2175f033b"
down_revision: str | Sequence[str] | None = "004b83fcafcb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events") as batch_op:
        batch_op.create_unique_constraint(
            "uq_events_project_source_reference",
            ["project_id", "source", "source_reference"],
        )
    with op.batch_alter_table("evidence") as batch_op:
        batch_op.create_unique_constraint(
            "uq_evidence_project_source_reference",
            ["project_id", "source", "reference"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evidence") as batch_op:
        batch_op.drop_constraint(
            "uq_evidence_project_source_reference",
            type_="unique",
        )

    with op.batch_alter_table("events") as batch_op:
        batch_op.drop_constraint(
            "uq_events_project_source_reference",
            type_="unique",
        )
    # ### end Alembic commands ###
