"""add interpretation runs

Revision ID: 9030269dd9ac
Revises: 8b14085b8c73
Create Date: 2026-10-03 10:46:51.295947

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9030269dd9ac"
down_revision: str | Sequence[str] | None = "8b14085b8c73"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interpretation_runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "interpretation_run_claims",
        sa.Column("interpretation_run_id", sa.String(), nullable=False),
        sa.Column("claim_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["knowledge_claims.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["interpretation_run_id"], ["interpretation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("interpretation_run_id", "claim_id"),
    )
    op.create_table(
        "interpretation_run_evidence",
        sa.Column("interpretation_run_id", sa.String(), nullable=False),
        sa.Column("evidence_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["interpretation_run_id"], ["interpretation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("interpretation_run_id", "evidence_id"),
        sa.UniqueConstraint("evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("interpretation_run_evidence")
    op.drop_table("interpretation_run_claims")
    op.drop_table("interpretation_runs")
    # ### end Alembic commands ###
