"""allow claims across document versions

Revision ID: 3382e88e4db2
Revises: 9030269dd9ac
Create Date: 2026-10-04 10:35:30.235335

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3382e88e4db2"
down_revision: str | Sequence[str] | None = "9030269dd9ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
