"""add knowledge claims

Revision ID: a393cc967881
Revises: 03b2175f033b
Create Date: 2026-10-02 10:55:01.008604

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a393cc967881"
down_revision: str | Sequence[str] | None = "03b2175f033b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_claims",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "confidence",
            sa.Enum("low", "medium", "high", name="claimconfidence"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "corrected", "invalidated", name="claimstatus"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_claim_evidence",
        sa.Column("claim_id", sa.String(), nullable=False),
        sa.Column("evidence_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["claim_id"], ["knowledge_claims.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["evidence_id"], ["evidence.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("claim_id", "evidence_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("knowledge_claim_evidence")
    op.drop_table("knowledge_claims")
    # ### end Alembic commands ###
